name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Install npm packages
      run: npm ci

    - name: Build web assets
      run: npm run build

    - name: Add Android platform
      run: npx cap add android

    - name: Capacitor Sync
      run: npx cap sync android

    - name: Build Android APK
      run: ./gradlew build
      working-directory: android

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk